openapi: 3.0.1
info:
  title: CJWAPI_V2
  version: 1.0.0
servers:
  - url: /
paths:
  /5f8ce6dd-1252-459a-8327-2e25196f5ea8:
    get:
      responses:
        '200':
          description: OK
   
      x-throttling-tier: Unlimited



x-wso2-production-endpoints:
  urls:
    - 'http://run.mocky.io/v3/'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://run.mocky.io/v3/'
  type: http
x-wso2-basePath: /bny/v2
x-wso2-disable-security: true
x-wso2-request-interceptor: java:mgw.interceptor.SampleInterceptor
x-wso2-response-interceptor: java:mgw.interceptor.SampleInterceptor
