FROM open-liberty:kernel-java11
COPY --chown=1001:0  target/1.1.7-SNAPSHOT.war /config/dropins/
COPY --chown=1001:0  server.xml /config/1.1.7-SNAPSHOT/1.1.7-SNAPSHOT
Testing  variables
1.1.7-SNAPSHOT
1.1.7-SNAPSHOT
